<?
	if ($lang == "nl") {
	$txt_faq = "FAQ";
	$txt_alt_backtop = "Terug naar hoofdpagina";
	$txt_header0 = "VRAGEN EN ANTWOORDEN";
	$txt_header1 = "Wat doet WebAgent?";
	$txt_header2 = "Wat houdt lidmaatschap in?";
	$txt_header3 = "Hoe beheer ik Mijn documenten?";
	$txt_header4 = "Hoe neem ik kontakt met jullie op?";
	$txt_header5 = "Kan ik WebAgent gebruiken als service op mijn site?";
	$txt_header6 = "Wetenswaardigheden..";
	$txt_content1 = "WebAgent onderhoudt een archief van webpagina's, oftwel documenten, die periodiek gecontroleerd worden op veranderingen in de inhoud. Zodra er een update is, voegt WebAgent alleen de <i>veranderde</i> inhoud toe aan zijn archief.<p>Dit archief is online te raadplegen voor leden en niet-leden. Voor niet-leden is alleen een publieke selectie uit het archief beschikbaar.<p>WebAgent kan bij elke verandering zijn leden op de hoogte brengen of nieuwsbrieven voor hen samenstellen.<p>WebAgent is een gloednieuwe dienst. Mocht je een fout tegenkomen in het gebruik, wil je deze dan a.u.b. melden op <a href=mailto:bugs@webagent.nl>bugs@webagent.nl</a>, waarvoor dank.<p>Lees meer over <a href=index.php?a=f&f=2>wat het lidmaatschap inhoudt</a>.";
	$txt_content2 = "Als lid krijg je je eigen archiefje van documenten die je zelf kunt toevoegen, verwijderen en uiteraard raadplegen.<p>Je kunt per document instellen of je tevens email wilt ontvangen bij een verandering en zoja hoe vaak je dan email wilt ontvangen. Het is ook mogelijk om een dagelijkse nieuwsbrief samen te stellen zodat je alle veranderingen in je archief slechts 1x per dag toegemaild krijgt.<p>Je kunt ook per document aangeven of je op zoek bent naar bepaalde keywords, of dat je bv. alleen geinteresseerd bent in geupdate plaatjes. Ook kun je bepaalde plekken (bv. menu's) uitsluiten.<p>Het lidmaatschap kost niets en je gegevens worden ook niet doorgegeven aan derden.<p>Je wordt lid door in het linkervenster je Emailadres in te vullen, een Wachtwoord te kiezen en het vinkje onder 'GEEN lid' aan te vinken. Je kunt dan meteen beginnen met documenten aan je archief toe te voegen.<p>Lees meer over <a href=index.php?a=f&f=3>hoe je documenten te beheren</a>.";
	$txt_content3 = "Er zijn twee manieren om documenten toe te voegen aan je archief:<ul><li>Ten eerste kun je uit de publieke catalogus een document kiezen en deze met een druk op <img src=img/mailinst_toevoeg_n.gif border=0> toevoegen.<li>Ten tweede kun je ook zelf een URL intikken in het 'Nieuw document' scherm. Je kunt kiezen om het eveneens in de publieke catalogus te tonen, of '--Prive--' te zetten.</ul>Een document verwijder je uit je archief door op <img src=img/delete_n.gif border=0> te drukken.<p>De mailinstellingen kun je benaderen door op <img src=img/mailinst_direkt_n.gif border=0> te drukken. Dan kun je het volgende instellen:<ul><li>Frequentie, kies uit meteen mailen voor elke update of laat de update toevoegen aan de dagelijkse (of tweedagelijkse) nieuwsbrief.<li>Keywords, als je er een of meerdere invult zal alleen de update opgestuurd worden als deze voorkomen.<li>Inhoud, de update zal alleen opgestuurd worden als deze bestaat uit een of meerdere links en/of tekst en/of afbeeldingen.<li>Lokatie, hiermee stel je bepaalde plekken in het document in, die genegeerd worden.</ul>Omdat je inhoud- en lokatieinstellingen als een soort persoonlijk interessefilter werken, zijn ze eveneens van toepassing bij het bekijken van het betreffende document archief op deze site. Standaard worden uit de inhoud de afbeeldingen genegeerd.<p>Mocht je opmerkingen of vragen hebben kun je altijd <a href=index.php?a=f&f=4>kontakt opnemen</a>.";
	$txt_content4 = "Voor opmerkingen en vragen kun je terecht bij<dl><dd><a href=mailto:info@webagent.nl>info@webagent.nl</a></dl><p>Indien je van mening bent dat een bepaald document of een bepaalde site niet mag worden gemonitord door WebAgent, meld dit dan bij<dl><dd><a href=mailto:ban@webagent.nl>ban@webagent.nl</a></dl><p>WebAgent is een initiatief van en geprogrammeerd door Jurgen Prins en wordt ondersteund door <a href=http://www.dds.nl/ target=_x>De Digitale Stad</a>.";
	$txt_content5 = "Wil je je gebruikers een <b>extra service</b> aanbieden? Biedt ze dan een <b>nieuwsbrief</b> aan met updates van je site! Het kost je <i>niets</i>.<p>Biedt een klein formulier aan op je site waar gebruikers hun emailadres invullen. Vervolgens worden ze automatisch door WebAgent van updates op je site op de hoogte gehouden. Zonder dat jij daar verder rekening mee hoeft te houden.<p>Bekijk eens het <b><a href=form/form.txt target=_x>voorbeeld aanmeldformulier</a></b>. Je ziet dat je al volstaat met alleen het veld 'url' aan te passen aan je eigen site.<p>WebAgent genereert zelf een wachtwoord voor de gebruiker, en meldt deze na de aanmelding op de resultaatpagina. Je kunt ook de gebruiker zelf een wachtwoord laten bedenken door het veld 'pw' in het formulier op te nemen. De gebruiker heeft het wachtwoord nodig om op de WebAgent site in te loggen, waar hij zijn wachtwoord en instellingen kan veranderen, en extra documenten toe kan voegen.<p>Je kunt de resultaatpagina's ook zelf maken. Hiervoor neem je het veld 'url_ok' en 'url_fail' op voor resp. geslaagde of mislukte aanmelding. Let wel dat specifieke WebAgent meldingen zoals het gegenereerde wachtwoord bij geslaagde aanmelding, of de exacte foutmelding bij mislukte aanmelding dan niet weergegeven worden.<p>In het <a href=form/form.txt target=_x>voorbeeld aanmeldformulier</a> kan alles wat niet gebruikt wordt en tussen (en inclusief) &lt;!-- en --&gt; staat, weggehaald worden. Het kleinste 'schone' formulier wat dan overblijft vind je <b><a href=form/form2.txt target=_x>hier</a></b>.<p>Als je je site ook in de publieke lijst op WebAgent wilt hebben, meldt dan zelf als eerste je site aan in een publieke categorie via 'Nieuw document'. Indien je niet weet hoe dit gaat, kun je dit nalezen bij informatie over <a href=index.php?a=f&f=2 target=_x>lidmaatschap</a> en <a href=index.php?a=f&f=3 target=_x>documentenbeheer</a>.<p>Indien je WebAgent in eigen huisstijl wilt gieten met eigen vormgeving, eigen categorieen enz., neem dan even kontakt op met <a href=mailto:info@webagent.nl>info@webagent.nl</a>.";
	$txt_content6 = "Waarom zijn in de archieven teksten afgebroken en links niet klikbaar?<ul><li>Als je alles kon lezen en direkt kon doorklikken zou er minder reden zijn om de betreffende site te bezoeken. Hierdoor kan WebAgent in de problemen komen met de makers van deze sites. Om dit te voorkomen zijn de teksten afgebroken en links niet klikbaar.</ul>Mijn archief en/of mail bevat echt bagger. Wat moet ik daarmee?<ul><li>Sommige documenten bestaan bv. uit alleen javascript. WebAgent kan daar (nog) niet mee uit de voeten en stuurt dan toegevoegde regels script door alsof het leesbare tekst is.<li>Sommige documenten updaten alleen hele specifieke informatie, bv. aantal km file. WebAgent stuurt dan alleen de (km) cijfers door, en dus uit zijn verband en dus onbegrijpelijk.<br>WebAgent is met name geschikt voor documenten waaraan regelmatig links of complete stukken tekst toegevoegd worden.</ul>Hoe komt WebAgent eigenlijk aan het geld om dit te draaien?<ul><li>Er zijn geen inkomsten. De Digitale Stad draait belangeloos deze dienst. Uiteraard is er hoop om in de toekomst op enige manier inkomsten te genereren, maar voorlopig is het gewoon een vriendendienst.</ul>Hoevaak en hoe controleert WebAgent een document?<ul><li>WebAgent controleert gemiddeld 7(!) keer per dag alle aangemelde documenten. Het merendeel van de keren meldt de webserver dat het document niet veranderd is. Indien wel of als de webserver het niet weet, haalt WebAgent het op en plukt alle teksten, links en plaatjes eruit en vergelijkt deze met de inhoud van zijn archief.</ul>Wat trekt zo'n site als dit nou?<ul><li>Ongeveer 500 unieke bezoekers per dag. Er komen per dag ongeveer 30 nieuwe leden bij. Er worden ongeveer 2000 mails per dag verstuurd. Er worden tegen de 5000 urls bijgehouden. Dit alles is nog steeds groeiende.. lees ook de <a href=pers.php target=_x>persmap</a>.</ul>Meer vragen? Mail <a href=\"mailto:info@webagent.nl\">info@webagent.nl</a>";
	} else {
	$txt_faq = "FAQ";
	$txt_alt_backtop = "Back to main page";
	$txt_header0 = "QUESTIONS AND ANSWERS";
	$txt_header1 = "What is WebAgent?";
	$txt_header2 = "What means membership for me?";
	$txt_header3 = "How do I manage My documents?";
	$txt_header4 = "How can I contact you?";
	$txt_header5 = "WebAgent for free as a service on your site?";
	$txt_header6 = "";
	$txt_content1 = "Webagent maintains an archive of webpages, documents, that are periodically checked for changes in content. When an update is detected, WebAgent adds the <i>changed</i> content to its archive.<p>The archive is available online for members and non-members. For non-members, only a public selection is available.<p>WebAgent is able to notify its member at each change or composing newsletters for them.<p>WebAgent is a brandnew service. If you encounter any errors while using it, please notify <a href=mailto:bugs@webagent.nl>bugs@webagent.nl</a>, thanks in advance.<p>Read more about <a href=index.php?a=f&f=2>what memberships means for you</a>.";
	$txt_content2 = "As member you get your own archive of documents to which you can add, remove and view the contents.<p>For each document you can receive email notification if you want. It is also possible to compose a daily newsletters so all changes will only be mailed once a day.<p>For each document you can also enter specific keywords to scan for or express your interest in e.g. only updated images. You can also ignore certain spots (e.g. menus).<p>Membership is free and your data is not being passed to third parties.<p>Become a member by filling your Email and picking a Password and check the box below 'NO membership?'. You can start adding documents immediately.<p>Read more about <a href=index.php?a=f&f=3>managing your documents</a>.";
	$txt_content3 = "There are two ways to add documents to your archive:<ul><li>First you can select one from the public archive and add it by clicking <img src=img/mailinst_toevoeg_n.gif border=0>.<li>Second, you can type an URL yourself in the 'New subscription' dialog. You can choose to also show it in the public archive, or keep it 'Private'.</ul>Remove a document by clicking <img src=img/delete_n.gif border=0>.<p>Tune your mailsettings by clicking <img src=img/mailinst_direkt_n.gif border=0>. You can change the following settings:<ul><li>Frequency, choose between direct mailing upon update or let the update be added to your (bi-)daily newsletter.<li>Keywords, if you specify one or more, the update will only be noted if these occur.<li>Content, the update will only be noted for the checked content types.<li>Location, specify certain spots in the document that will be ignored for you.</ul>Because the content and location settings work like a personal interest filter, they also apply while viewing the document archive on this site. By default, images in the content are ignored.<p>If you have comments or suggestions you can always <a href=index.php?a=f&f=4>contact us</a>.";
	$txt_content4 = "If you have comments or suggestions, direct them to<dl><dd><a href=mailto:info@webagent.nl>info@webagent.nl</a></dl><p>If you feel a specific document or specific site should not be monitored by WebAgent, please notify<dl><dd><a href=mailto:ban@webagent.nl>ban@webagent.nl</a></dl><p>WebAgent is supported by <a href=http://www.dds.nl/ target=_x>The Digital City</a>.";
	$txt_content5 = "At the moment, WebAgent as a free service for your website is only available in dutch. You may read the dutch guidelines by clicking NL in the left-top of this page or do it <a href=index.php?a=f&f=5&l=nl>here</a>.";
	$txt_content6 = "At the moment, there is no English translation. Besides it is not really important anyway ;-)";
	}
?>
